package com.example.tinypeace.model.enums

enum class Language(val emoji: String, val description: String) {
    ENGLISH("🇬🇧", "English"),
    SPANISH("🇪🇸", "Spanish"),
    CHINESE("🇨🇳", "Chinese"),
    HINDI("🇮🇳", "Hindi"),
    ARABIC("🇸🇦", "Arabic"),
    PORTUGUESE("🇵🇹", "Portuguese"),
    BENGALI("🇧🇩", "Bengali"),
    RUSSIAN("🇷🇺", "Russian"),
    JAPANESE("🇯🇵", "Japanese"),
    GERMAN("🇩🇪", "German"),
    FRENCH("🇫🇷", "French"),
    URDU("🇵🇰", "Urdu"),
    SWAHILI("🇰🇪", "Swahili"),
    ITALIAN("🇮🇹", "Italian"),
    TURKISH("🇹🇷", "Turkish"),
    KOREAN("🇰🇷", "Korean"),
    DUTCH("🇳🇱", "Dutch"),
    POLISH("🇵🇱", "Polish"),
    VIETNAMESE("🇻🇳", "Vietnamese"),
    THAI("🇹🇭", "Thai"),
    PERSIAN("🇮🇷", "Persian"),
    MALAY("🇲🇾", "Malay"),
    UKRAINIAN("🇺🇦", "Ukrainian"),
    GREEK("🇬🇷", "Greek"),
    HUNGARIAN("🇭🇺", "Hungarian"),
    CZECH("🇨🇿", "Czech"),
    SWEDISH("🇸🇪", "Swedish"),
    DANISH("🇩🇰", "Danish"),
    FINNISH("🇫🇮", "Finnish"),
    NORWEGIAN("🇳🇴", "Norwegian"),
}
