package com.example.tinypeace.enums

enum class CollegeMajor(val emoji: String, val description: String) {
    EDUCATION("🎓", "Education"),
    HISTORY("🏛️", "History"),
    LITERATURE("📚", "Literature"),
    ECONOMICS("📊", "Economics"),
    BUSINESS_ADMINISTRATION("💼", "Business Administration"),
    COMPUTER_SCIENCE("🖥️", "Computer Science"),
    MOBILE_DEVELOPMENT("📱", "Mobile Development"),
    AEROSPACE_ENGINEERING("📡", "Aerospace Engineering"),
    CIVIL_ENGINEERING("🏗️", "Civil Engineering"),
    MECHANICAL_ENGINEERING("🚂", "Mechanical Engineering"),
    BIOLOGY("🧬", "Biology"),
    CHEMISTRY("🧪", "Chemistry"),
    ENVIRONMENTAL_SCIENCE("🌍", "Environmental Science"),
    FINANCE("📈", "Finance"),
    JOURNALISM("📝", "Journalism"),
    FILM_STUDIES("🎬", "Film Studies"),
    PERFORMING_ARTS("🎭", "Performing Arts"),
    FINE_ARTS("🎨", "Fine Arts"),
    MUSIC("🎤", "Music"),
    MUSIC_PERFORMANCE("🎻", "Music Performance"),
    GEOGRAPHY("🗺️", "Geography"),
    POLITICAL_SCIENCE("📰", "Political Science"),
    AGRICULTURE("🚜", "Agriculture"),
    CONSTRUCTION("🚧", "Construction"),
    MANUFACTURING("🏭", "Manufacturing"),
    TELECOMMUNICATIONS("📡", "Telecommunications"),
    LOGISTICS("🚚", "Logistics"),
    TRADES("🛠️", "Trades"),
    HEALTHCARE("🏥", "Healthcare"),
    LIBERAL_ARTS("🎓", "Liberal Arts"),
    FORESTRY("🌳", "Forestry"),
    CULINARY_ARTS("🍽️", "Culinary Arts"),
    INFORMATION_TECHNOLOGY("📱", "Information Technology"),
    CREATIVE_WRITING("📝", "Creative Writing"),
    PSYCHOLOGY("🧠", "Psychology"),
    MATHEMATICS("🧮", "Mathematics"),
    REAL_ESTATE("🏢", "Real Estate"),
    GAMING_INDUSTRY("🎲", "Gaming Industry"),
    RETAIL("🛒", "Retail"),
    TRANSPORTATION("🚛", "Transportation"),
    MEDIA_STUDIES("📡", "Media Studies"),
    BOTANY("🌱", "Botany"),
    EVENT_MANAGEMENT("🎪", "Event Management")
}
