package com.example.tinypeace.enums

enum class Interest(val emoji: String, val description: String) {
    SPORTS("⚽", "Sports"),
    MUSIC("🎵", "Music"),
    TRAVEL("✈️", "Travel"),
    GAMING("🎮", "Gaming"),
    READING("📚", "Reading"),
    COOKING("🍳", "Cooking"),
    MOVIES("🎬", "Movies"),
    FITNESS("💪", "Fitness"),
    ART("🎨", "Art"),
    PHOTOGRAPHY("📸", "Photography"),
    TECHNOLOGY("💻", "Technology"),
    FASHION("👗", "Fashion"),
    GARDENING("🌱", "Gardening"),
    DIY("🛠️", "DIY"),
    ANIMALS("🐶", "Animals"),
    CARS("🚗", "Cars"),
    FOOD("🍔", "Food"),
    FISHING("🎣", "Fishing"),
    HIKING("🥾", "Hiking"),
    CYCLING("🚴", "Cycling"),
    SWIMMING("🏊", "Swimming"),
    RUNNING("🏃", "Running"),
    DANCING("💃", "Dancing"),
    YOGA("🧘", "Yoga"),
    MEDITATION("🧘‍♂️", "Meditation"),
    CAMPING("🏕️", "Camping"),
    BOARD_GAMES("🎲", "Board Games"),
    PUZZLES("🧩", "Puzzles"),
    CRAFTING("✂️", "Crafting"),
    KNITTING("🧶", "Knitting"),
    WRITING("✍️", "Writing"),
    POETRY("📜", "Poetry"),
    CALLIGRAPHY("🖋️", "Calligraphy"),
    BIRD_WATCHING("🐦", "Bird Watching"),
    ASTRONOMY("🔭", "Astronomy"),
    SCIENCE("🔬", "Science"),
    MAGIC("🪄", "Magic"),
    HISTORY("🏛️", "History"),
    ANTIQUES("🪑", "Antiques"),
    TRIVIA("❓", "Trivia"),
    THEATER("🎭", "Theater"),
    OPERA("🎼", "Opera"),
    BALLET("🩰", "Ballet"),
    CLASSICAL_MUSIC("🎻", "Classical Music"),
    JAZZ("🎷", "Jazz"),
    ROCK_MUSIC("🎸", "Rock Music"),
    ELECTRONIC_MUSIC("🎧", "Electronic Music"),
    PHILOSOPHY("📖", "Philosophy"),
    LANGUAGES("🗣️", "Languages"),
    VOLUNTEERING("🤝", "Volunteering"),
    INVESTING("💸", "Investing"),
    CRYPTOCURRENCY("🪙", "Cryptocurrency"),
    WOODWORKING("🪵", "Woodworking"),
    METALWORKING("⚙️", "Metalworking"),
    POTTERY("🏺", "Pottery"),
    PAINTING("🖼️", "Painting"),
    VIDEO_EDITING("🎥", "Video Editing"),
    PODCASTING("🎙️", "Podcasting"),
    VLOGGING("📹", "Vlogging"),
    BLOGGING("📝", "Blogging"),
    MODEL_BUILDER("🚂", "Model Building"),
    RC_CARS("🚗", "RC Cars"),
    DRONES("🚁", "Drones"),
    SURFING("🏄", "Surfing"),
    SKATEBOARDING("🛹", "Skateboarding"),
    SKIING("🎿", "Skiing"),
    SNOWBOARDING("🏂", "Snowboarding"),
    ROCK_CLIMBING("🧗", "Rock Climbing"),
    SCUBA_DIVING("🤿", "Scuba Diving"),
    SAILING("⛵", "Sailing"),
    MOTORCYCLES("🏍️", "Motorcycles"),
    HORSE_RIDING("🏇", "Horse Riding"),
    ESPORTS("🕹️", "Esports"),
    MARTIAL_ARTS("🥋", "Martial Arts"),
    PARKOUR("🤸", "Parkour"),
    ARCHERY("🏹", "Archery"),
    FENCING("🤺", "Fencing"),
    LACROSSE("🥍", "Lacrosse"),
    RUGBY("🏉", "Rugby"),
    BASEBALL("⚾", "Baseball"),
    AMERICAN_FOOTBALL("🏈", "American Football"),
    BASKETBALL("🏀", "Basketball"),
    TENNIS("🎾", "Tennis"),
    BADMINTON("🏸", "Badminton"),
    GOLF("🏌️", "Golf"),
    TABLE_TENNIS("🏓", "Table Tennis"),
    SQUASH("⚫", "Squash"),
    HAND_BALL("🤾", "Handball"),
    WATER_POLO("🤽", "Water Polo"),
    ICE_SKATING("⛸️", "Ice Skating"),
    HOCKEY("🏒", "Hockey"),
    CURLING("🥌", "Curling"),
    CHESS("♟️", "Chess"),
    TAROT("🔮", "Tarot"),
    COSPLAY("👾", "Cosplay"),
    GEOCACHING("🗺️", "Geocaching"),
    STARGAZING("🌌", "Stargazing"),
    KARAOKE("🎤", "Karaoke"),
    SUDOKU("🔢", "Sudoku"),
    ESCAPE_ROOMS("🔐", "Escape Rooms"),
    AXE_THROWING("🪓", "Axe Throwing"),
    KITESURFING("🪁", "Kitesurfing"),
    PARAGLIDING("🪂", "Paragliding"),
    SKETCHING("✏️", "Sketching"),
    COMIC_BOOKS("📚", "Comic Books"),
    GRAFFITI("🖍️", "Graffiti"),
    STAND_UP_COMEDY("🎤", "Stand-up Comedy"),
    SPACE_EXPLORATION("🚀", "Space Exploration"),
    DRONE_FLYING("🚁", "Drone Flying"),
    BIOGRAPHIES("📖", "Biographies"),
    MYTHOLOGY("📜", "Mythology"),
    BEER_BREWING("🍺", "Beer Brewing"),
    WINEMAKING("🍷", "Winemaking"),
    CHEESEMAKING("🧀", "Cheesemaking"),
    HUNTING("🏹", "Hunting"),
    KNIFE_COLLECTING("🔪", "Knife Collecting"),
    STAMP_COLLECTING("📮", "Stamp Collecting"),
    COIN_COLLECTING("🪙", "Coin Collecting"),
    ROLLER_SKATING("🛼", "Roller Skating"),
    INLINE_SKATING("🎢", "Inline Skating"),
    WATERSKIING("🎿", "Waterskiing"),
    WAKEBOARDING("🏄", "Wakeboarding"),
    RAFTING("🚣", "Rafting"),
    BUNGEE_JUMPING("🪂", "Bungee Jumping"),
    SKYDIVING("🪂", "Skydiving"),
    GLIDING("🛩️", "Gliding"),
    HOT_AIR_BALLOONING("🎈", "Hot Air Ballooning"),
    POWERLIFTING("🏋️", "Powerlifting"),
    CROSS_FIT("🏋️", "Cross Fit"),
    PILATES("🧘", "Pilates"),
    SPINNING("🚴", "Spinning"),
    ZUMBA("💃", "Zumba"),
    AEROBICS("🏋️", "Aerobics"),
    BOWLING("🎳", "Bowling"),
    DARTS("🎯", "Darts"),
    BILLIARDS("🎱", "Billiards"),
    POOL("🎱", "Pool"),
    KAYAKING("🛶", "Kayaking"),
    CANOEING("🛶", "Canoeing"),
    JET_SKIING("🛥️", "Jet Skiing"),
    SNORKELING("🤿", "Snorkeling"),
    BODYBOARDING("🏄", "Bodyboarding"),
    WINDSURFING("🏄", "Windsurfing"),
    BEACH_VOLLEYBALL("🏐", "Beach Volleyball"),
    PICKLEBALL("🏓", "Pickleball"),
    HANDBALL("🤾", "Handball"),
    TRAMPOLINING("🤸", "Trampolining"),
    NETBALL("🏀", "Netball"),
    GAELIC_FOOTBALL("🏐", "Gaelic Football"),
    HURLING("🏑", "Hurling"),
    ROLLER_DERBY("🏒", "Roller Derby"),
    SPEED_SKATING("⛸️", "Speed Skating"),
    FIGURE_SKATING("⛸️", "Figure Skating"),
    ICE_HOCKEY("🏒", "Ice Hockey"),
    FLOORBALL("🏒", "Floorball"),
    BANDY("🏑", "Bandy"),
    KABBADI("🤼", "Kabbadi"),
    SUMO_WRESTLING("🤼", "Sumo Wrestling"),
    MUAY_THAI("🥋", "Muay Thai"),
    KRAV_MAGA("🥋", "Krav Maga"),
    JUDO("🥋", "Judo"),
    AIKIDO("🥋", "Aikido"),
    CAPOEIRA("🥋", "Capoeira"),
    SAMBO("🥋", "Sambo"),
    KENDO("🥋", "Kendo"),
    WRESTLING("🤼", "Wrestling"),
    BOXING("🥊", "Boxing"),
    KICKBOXING("🥊", "Kickboxing"),
    TAICHI("🧘", "Tai Chi"),
    QIGONG("🧘", "Qigong"),
    FALCONRY("🦅", "Falconry"),
    GUN_COLLECTING("🔫", "Gun Collecting"),
    SURVIVALISM("🏕️", "Survivalism"),
    BUSHCRAFT("🏕️", "Bushcraft"),
    AIRSOFT("🔫", "Airsoft"),
    PAINTBALL("🔫", "Paintball"),
    ZIPLINING("🚡", "Ziplining"),
    BASE_JUMPING("🪂", "BASE Jumping"),
    CAVING("🦇", "Caving"),
    ROCK_HOUNDING("🪨", "Rock Hounding"),
    METAL_DETECTING("🔍", "Metal Detecting"),
    GOLD_PROSPECTING("💰", "Gold Prospecting"),
    GHOST_HUNTING("👻", "Ghost Hunting"),
    UFOLOGIST("👽", "Ufologist"),
    CRYPTOZOOLOGY("🦄", "Cryptozoology"),
    PARANORMAL_INVESTIGATION("👻", "Paranormal Investigation"),
    MYCOLOGY("🍄", "Mycology"),
    ENTOMOLOGY("🐜", "Entomology"),
    HERPETOLOGY("🐍", "Herpetology"),
    BOTANY("🌿", "Botany"),
    ORNITHOLOGY("🐦", "Ornithology"),
    ASTROPHOTOGRAPHY("🌌", "Astrophotography"),
    STORM_CHASING("🌪️", "Storm Chasing"),
    AURORA_CHASING("🌌", "Aurora Chasing"),
    SHIP_SPOTTING("🚢", "Ship Spotting"),
    TRAIN_SPOTTING("🚂", "Train Spotting"),
    PLANE_SPOTTING("✈️", "Plane Spotting"),
    GRAFFITI_ART("🖍️", "Graffiti Art"),
    TATTOO_ART("💉", "Tattoo Art"),
    BLACKSMITHING("⚒️", "Blacksmithing"),
    LEATHERWORK("👞", "Leatherwork"),
    TEXTILE_ART("🧵", "Textile Art"),
    GLASSBLOWING("🔥", "Glassblowing"),
    MOSAIC_ART("🖼️", "Mosaic Art"),
    CERAMICS("🏺", "Ceramics"),
    SCULPTURE("🗿", "Sculpture"),
    MIXED_MEDIA_ART("🎨", "Mixed Media Art"),
    PRINTMAKING("🖨️", "Printmaking"),
    COLLAGE_ART("🖼️", "Collage Art"),
    CALLIGRAPHY_ART("🖋️", "Calligraphy Art"),
    STREET_ART("🖍️", "Street Art"),
    STAMP_ART("📮", "Stamp Art"),
    STICKER_ART("📒", "Sticker Art"),
    MINIATURE_ART("🖼️", "Miniature Art"),
    CHALK_ART("🖍️", "Chalk Art"),
    SHADOW_ART("🖼️", "Shadow Art"),
    STRING_ART("🧵", "String Art"),
    ORIGAMI("🧩", "Origami"),
    PAPER_CRAFT("✂️", "Paper Craft"),
    SCRAPBOOKING("📒", "Scrapbooking"),
    QUILTING("🧵", "Quilting"),
    EMBROIDERY("🧵", "Embroidery"),
    FELTING("🧶", "Felting"),
    SPINNING_WOOL("🧶", "Spinning Wool"),
    TATTOO_COLLECTING("💉", "Tattoo Collecting"),
    SNEAKER_COLLECTING("👟", "Sneaker Collecting"),
    VINTAGE_CLOTHING("👗", "Vintage Clothing"),
    PIN_COLLECTING("📌", "Pin Collecting"),
    BUTTON_COLLECTING("🔘", "Button Collecting"),
    FIGURINE_COLLECTING("🧸", "Figurine Collecting"),
    COMIC_BOOK_COLLECTING("📚", "Comic Book Collecting"),
    ACTION_FIGURE_COLLECTING("🧸", "Action Figure Collecting"),
    VINTAGE_TOYS("🧸", "Vintage Toys"),
    PLAYING_CARD_COLLECTING("🃏", "Playing Card Collecting"),
    TAROT_CARD_COLLECTING("🔮", "Tarot Card Collecting"),
    POSTCARD_COLLECTING("✉️", "Postcard Collecting"),
    AUTOGRAPH_COLLECTING("✍️", "Autograph Collecting"),
    SIGNATURE_COLLECTING("✍️", "Signature Collecting"),
    MEMORABILIA_COLLECTING("🧸", "Memorabilia Collecting"),
    KITE_FLYING("🪁", "Kite Flying"),
    PAPER_PLANES("✈️", "Paper Planes"),
    BALLOON_MODELLING("🎈", "Balloon Modelling"),
    JUGGLING("🤹", "Juggling"),
    YO_YO("🪀", "Yo-Yo"),
    MAGIC_TRICKS("🪄", "Magic Tricks"),
    MIME("🤹", "Mime"),
    CLOWNING("🤡", "Clowning"),
    STILT_WALKING("🥾", "Stilt Walking"),
    FIRE_BREATHING("🔥", "Fire Breathing"),
    SWORD_SWALLOWING("🗡️", "Sword Swallowing"),
    ESCAPE_ARTISTRY("🔐", "Escape Artistry"),
    VENTRILOQUISM("🗣️", "Ventriloquism"),
    FACE_PAINTING("🎨", "Face Painting"),
    BODY_PAINTING("🎨", "Body Painting"),
    HENNA("🖋️", "Henna"),
    TEMPORARY_TATTOOS("🎨", "Temporary Tattoos"),
    NAIL_ART("💅", "Nail Art"),
    MAKEUP_ART("💄", "Makeup Art"),
    COSMETOLOGY("💄", "Cosmetology"),
    BEAUTY_GURU("💄", "Beauty Guru"),
    HAIR_STYLING("💇", "Hair Styling"),
    BARBERING("💈", "Barbering"),
    PERFUMERY("🌸", "Perfumery"),
    JEWELRY_MAKING("💍", "Jewelry Making"),
    BEADWORK("📿", "Beadwork"),
    LAPIDARY("💎", "Lapidary"),
    WATCH_COLLECTING("⌚", "Watch Collecting"),
    WRISTWATCH_COLLECTING("⌚", "Wristwatch Collecting"),
    POCKET_WATCH_COLLECTING("⌚", "Pocket Watch Collecting"),
    FOUNTAIN_PEN_COLLECTING("🖋️", "Fountain Pen Collecting"),
    CAMERA_COLLECTING("📸", "Camera Collecting"),
    MUSICAL_INSTRUMENT_COLLECTING("🎷", "Musical Instrument Collecting"),
    VIOLIN("🎻", "Violin"),
    PIANO("🎹", "Piano"),
    GUITAR("🎸", "Guitar"),
    DRUMS("🥁", "Drums"),
    FLUTE("🎶", "Flute"),
    TRUMPET("🎺", "Trumpet"),
    CELLO("🎻", "Cello"),
    SAXOPHONE("🎷", "Saxophone"),
    CLARINET("🎶", "Clarinet"),
    HARP("🎶", "Harp"),
    SYNTHESIZER("🎹", "Synthesizer"),
    DJING("🎧", "DJing"),
    RECORD_COLLECTING("💿", "Record Collecting"),
    VINYL_COLLECTING("💿", "Vinyl Collecting"),
    CASSETTE_COLLECTING("💿", "Cassette Collecting"),
    CD_COLLECTING("💿", "CD Collecting"),
    MUSIC_PRODUCTION("🎶", "Music Production"),
    SONGWRITING("🎶", "Songwriting"),
    COMPOSING("🎼", "Composing"),
    CONDUCTING("🎼", "Conducting"),
    MUSIC_TEACHING("🎶", "Music Teaching"),
    BAND("🎷", "Band"),
    ORCHESTRA("🎼", "Orchestra"),
    CHOIR("🎤", "Choir"),
    OPERA_SINGING("🎼", "Opera Singing"),
    THEATER_ACTING("🎭", "Theater Acting"),
    MUSICAL_THEATER("🎭", "Musical Theater"),
    BALLET_DANCING("🩰", "Ballet Dancing"),
    ARGENTINE_TANGO("🇦🇷", "Argentine Tango"),
    BRAZILIAN_SAMBA("🇧🇷", "Brazilian Samba"),
    CUBAN_SALSA("🇨🇺", "Cuban Salsa"),
    FLAMENCO("🇪🇸", "Flamenco"),
    BOLLYWOOD("🇮🇳", "Bollywood"),
    KATHAK("🇮🇳", "Kathak"),
    BHARATANATYAM("🇮🇳", "Bharatanatyam"),
    ODISSI("🇮🇳", "Odissi"),
    KATHAKALI("🇮🇳", "Kathakali"),
    MOHINIYATTAM("🇮🇳", "Mohiniyattam"),
    KUCHIPUDI("🇮🇳", "Kuchipudi"),
    MANIPURI("🇮🇳", "Manipuri"),
    SATTRIYA("🇮🇳", "Sattriya"),
    CHINESE_OPERA("🇨🇳", "Chinese Opera"),
    PUPPETRY("🤹", "Puppetry"),
    MARIONETTES("🤹", "Marionettes"),
    SHADOW_PUPPETS("🤹", "Shadow Puppets"),
    HAND_PUPPETS("🤹", "Hand Puppets"),
    FINGER_PUPPETS("🤹", "Finger Puppets"),
    PUPPET_MAKING("🤹", "Puppet Making"),
    MASK_MAKING("🎭", "Mask Making"),
    PROP_MAKING("🎭", "Prop Making"),
    COSTUME_DESIGN("👗", "Costume Design"),
    SET_DESIGN("🎭", "Set Design"),
    STAGE_MANAGEMENT("🎭", "Stage Management"),
    LIGHTING_DESIGN("🎭", "Lighting Design"),
    SOUND_DESIGN("🎭", "Sound Design"),
    SPECIAL_EFFECTS("🎭", "Special Effects"),
    PYROTECHNICS("🎭", "Pyrotechnics"),
    MAKEUP_ARTISTRY("💄", "Makeup Artistry"),
    WIG_MAKING("💇", "Wig Making"),
    HAIRSTYLING("💇", "Hairstyling"),
    WARDROBE_SUPERVISING("👗", "Wardrobe Supervising"),
    STAGE_COMBAT("🥋", "Stage Combat"),
    STUNT_PERFORMING("🥋", "Stunt Performing"),
    MASK_WORK("🎭", "Mask Work"),
    COMMEDIA_DELL_ARTE("🎭", "Commedia Dell'arte"),
    IMPROV("🎭", "Improv"),
    SKETCH_COMEDY("🎭", "Sketch Comedy"),
    STANDUP_COMEDY("🎭", "Standup Comedy"),
    SATIRE("🎭", "Satire"),
    PARODY("🎭", "Parody"),
    FARCE("🎭", "Farce"),
    COMEDY("🎭", "Comedy"),
    DRAMA("🎭", "Drama"),
    TRAGEDY("🎭", "Tragedy"),
    OPERETTA("🎭", "Operetta")
}
