package com.example.tinypeace.enums

enum class Nationality(val emoji: String, val description: String) {
    AMERICAN("🇺🇸", "American"),
    CHINESE("🇨🇳", "Chinese"),
    INDIAN("🇮🇳", "Indian"),
    JAPANESE("🇯🇵", "Japanese"),
    RUSSIAN("🇷🇺", "Russian"),
    BRAZILIAN("🇧🇷", "Brazilian"),
    FRENCH("🇫🇷", "French"),
    GERMAN("🇩🇪", "German"),
    BRITISH("🇬🇧", "British"),
    SPANISH("🇪🇸", "Spanish"),
    ITALIAN("🇮🇹", "Italian"),
    KOREAN("🇰🇷", "Korean"),
    CANADIAN("🇨🇦", "Canadian"),
    AUSTRALIAN("🇦🇺", "Australian"),
    MEXICAN("🇲🇽", "Mexican"),
    SOUTH_AFRICAN("🇿🇦", "South African"),
    NIGERIAN("🇳🇬", "Nigerian"),
    SAUDI_ARABIAN("🇸🇦", "Saudi Arabian"),
    ARGENTINE("🇦🇷", "Argentine"),
    DUTCH("🇳🇱", "Dutch"),
    INDONESIAN("🇮🇩", "Indonesian"),
    EGYPTIAN("🇪🇬", "Egyptian"),
    GREEK("🇬🇷", "Greek"),
    POLISH("🇵🇱", "Polish"),
    SWEDISH("🇸🇪", "Swedish"),
    PAKISTANI("🇵🇰", "Pakistani"),
    FILIPINO("🇵🇭", "Filipino"),
    CHILEAN("🇨🇱", "Chilean"),
    TURKISH("🇹🇷", "Turkish"),
    VIETNAMESE("🇻🇳", "Vietnamese"),
    EMIRATI("🇦🇪", "Emirati"),
    JORDANIAN("🇯🇴", "Jordanian"),
    THAI("🇹🇭", "Thai"),
    IRISH("🇮🇪", "Irish"),
    NORWEGIAN("🇳🇴", "Norwegian"),
    FINNISH("🇫🇮", "Finnish"),
    DANISH("🇩🇰", "Danish"),
    HUNGARIAN("🇭🇺", "Hungarian"),
    BELGIAN("🇧🇪", "Belgian"),
    AUSTRIAN("🇦🇹", "Austrian"),
    SWISS("🇨🇭", "Swiss"),
    PORTUGUESE("🇵🇹", "Portuguese"),
    CZECH("🇨🇿", "Czech"),
    SLOVAK("🇸🇰", "Slovak"),
    SERBIAN("🇷🇸", "Serbian"),
    CROATIAN("🇭🇷", "Croatian"),
    BULGARIAN("🇧🇬", "Bulgarian"),
    ROMANIAN("🇷🇴", "Romanian"),
    LITHUANIAN("🇱🇹", "Lithuanian"),
    LATVIAN("🇱🇻", "Latvian"),
    ESTONIAN("🇪🇪", "Estonian"),
    KUWAITI("🇰🇼", "Kuwaiti"),
    QATARI("🇶🇦", "Qatari"),
    OMANI("🇴🇲", "Omani"),
    MOROCCAN("🇲🇦", "Moroccan"),
    TUNISIAN("🇹🇳", "Tunisian"),
    ALGERIAN("🇩🇿", "Algerian"),
    ECUADORIAN("🇪🇨", "Ecuadorian"),
    COSTA_RICAN("🇨🇷", "Costa Rican"),
    COLOMBIAN("🇨🇴", "Colombian"),
    PERUVIAN("🇵🇪", "Peruvian"),
    URUGUAYAN("🇺🇾", "Uruguayan"),
    SALVADORAN("🇸🇻", "Salvadoran"),
    VENEZUELAN("🇻🇪", "Venezuelan"),
    PANAMANIAN("🇵🇦", "Panamanian"),
    BOLIVIAN("🇧🇴", "Bolivian"),
    PARAGUAYAN("🇵🇾", "Paraguayan"),
    NICARAGUAN("🇳🇮", "Nicaraguan"),
    HONDURAN("🇭🇳", "Honduran"),
    DOMINICAN_("🇩🇴", "Dominican"),
    CUBAN("🇨🇺", "Cuban"),
    PUERTO_RICAN("🇵🇷", "Puerto Rican"),
    BELIZEAN("🇧🇿", "Belizean"),
    BAHAMIAN("🇧🇸", "Bahamian"),
    JAMAICAN("🇯🇲", "Jamaican"),
    HAITIAN("🇭🇹", "Haitian"),
    GUYANESE("🇬🇾", "Guyanese"),
    SURINAMESE("🇸🇷", "Surinamese"),
    TRINIDADIAN_TOBAGONIAN("🇹🇹", "Trinidadian/Tobagonian"),
    GRENADIAN("🇬🇩", "Grenadian"),
    BARBADIAN("🇧🇧", "Barbadian"),
    SAINT_LUCIAN("🇱🇨", "Saint Lucian"),
    VINCENTIAN("🇻🇨", "Vincentian"),
    ANTIGUAN_BARBUDAN("🇦🇬", "Antiguan/Barbudan"),
    SAINT_KITTS_NEVISIAN("🇰🇳", "Saint Kitts and Nevisian"),
    DOMINICAN("🇩🇲", "Dominican")
}
